name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The tests have run."
  trigger-deploy:
    name: Trigger deploy
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
    steps:
      - name: Trigger deployment
        id: trigger-deployment
        run: |
          gh api /repos/${{ github.repository }}/deployments \
           -f ref='${{ github.ref }}' \
           -f description='Deploy request from CI Workflow' \
           -f environment='integration' \
           -F required_contexts=[] \
           -F auto_merge='false'
