name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The tests have run."
    #uses: alphagov/govuk-infrastructure/.github/workflows/ci.yaml@add-ci-workflow
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    needs: test
    uses: alphagov/govuk-infrastructure/.github/workflows/release.yaml@add-ci-workflow
