name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The tests have run."
  trigger-deploy:
    name: Trigger deploy
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
    steps:
      - name: Trigger deployment
        id: trigger-deployment
        run: |
          read -r -d '' DATA << EOM
            {
               "ref": "${{ github.ref }}",
               "description": "Deploy request from CI Workflow",
               "environment": "integration",
               "required_contexts": [],
               "auto_merge": false
            }
          EOM
          echo "$DATA" | gh api repos/${{ github.repository }}/deployments --input -
#
#         echo '{
#            "ref": "${{ github.ref }}",
#            "description": "Deploy request from CI Workflow",
#            "environment": "integration",
#            "required_contexts": [],
#            "auto_merge": false
#          }' | gh api repos/${{ github.repository }}/deployments --input -
