name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    uses: alphagov/govuk-infrastructure/.github/workflows/ci.yaml@add-ci-workflow
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    needs: test
    uses: alphagov/govuk-infrastructure/.github/workflows/release.yaml@add-ci-workflow
